# render.yaml - configuration for Render.com deployment

services:
  - type: web
    name: django-web
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn projeto_integrador.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        value: "mongodb+srv://Santana:123sdf45@cluster0.ioua4vr.mongodb.net/?appName=Cluster0"
