# Generated by Django 6.0.2 on 2026-03-05 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
