# Generated by Django 6.0.2 on 2026-03-07 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_comment_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='is_like',
            field=models.BooleanField(default=True),
        ),
    ]
