# Generated by Django 6.0.2 on 2026-03-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_remove_commentlike_post_comment_parent_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reports',
        ),
    ]
