# Generated by Django 6.0.2 on 2026-03-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='phone',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='ddd',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino'), ('Outro', 'Outro'), ('Prefiro não dizer', 'Prefiro não dizer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sexuality',
            field=models.CharField(choices=[('Heterossexual', 'Heterossexual'), ('Homossexual', 'Homossexual'), ('Bissexual', 'Bissexual'), ('Assexual', 'Assexual'), ('Outro', 'Outro'), ('Prefiro não dizer', 'Prefiro não dizer')], max_length=20),
        ),
    ]
