# Generated by Django 6.0.2 on 2026-02-28 16:08

import br_utils.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_phone_is_mobile_alter_user_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='address',
            name='cep',
            field=br_utils.models.BRPostalCodeField(max_length=9),
        ),
        migrations.AlterField(
            model_name='user',
            name='cpf',
            field=br_utils.models.BRCPFField(max_length=14, unique=True),
        ),
    ]
