"""
Django settings for projeto_integrador project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# pulled from environment for deploy platforms like Render
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-eg7$e41o7=(byz!50d&u5nv@a4iacqg63z)j6tt!a&a0r8o54h')

# SECURITY WARNING: don't run with debug turned on in production!
# configure via environment variable, treat 'False' string as False
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') != 'False'

# allow hosts from environment variables, default localhost and local IP
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'ecoa.onrender.com']
# include render specific hostname if present
render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if render_host:
    ALLOWED_HOSTS.append(render_host)
# include other provided hosts from comma-separated env var
extra_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS')
if extra_hosts:
    ALLOWED_HOSTS.extend(extra_hosts.split(','))
# ensure it's a unique list
ALLOWED_HOSTS = list(set(ALLOWED_HOSTS))

# Add CSRF trusted origins for production
CSRF_TRUSTED_ORIGINS = ['https://ecoa.onrender.com']
if render_host:
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_host}')



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'pictures',
    'courses',
    'forum',
    'authorization',
    'payments',
    'notifications',
    'reports',
    'chatbot',
    'django_mongodb_backend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # enable Whitenoise to serve static files in production
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Middleware customizado para segurança (IP e Bloqueio)
    'core.middleware.UserSecurityMiddleware',
]


ROOT_URLCONF = 'projeto_integrador.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.notifications',
            ],
        },
    },
]

WSGI_APPLICATION = 'projeto_integrador.wsgi.application'


# Database configuration and patches
if DEBUG and not os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
else:
    # Import models here to avoid early initialization issues
    from django.db import models
    # Patch models to use MongoDB ObjectId for all automatic IDs (Admin, Auth, etc)
    import django_mongodb_backend.fields
    models.AutoField = django_mongodb_backend.fields.ObjectIdAutoField
    models.BigAutoField = django_mongodb_backend.fields.ObjectIdAutoField

    DATABASES = {
        'default': {
            'ENGINE': 'django_mongodb_backend',
            'NAME': 'projeto_integrador',
            'HOST': os.environ.get('DATABASE_URL', 'mongodb+srv://Santana:123sdf45@cluster0.ioua4vr.mongodb.net/?appName=Cluster0'),
        }
    }
    DEFAULT_AUTO_FIELD = 'django_mongodb_backend.fields.ObjectIdAutoField'

# Logging configuration for production to help find 500 errors
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'django': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
        'propagate': True,
    },
}


#cache
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Logging configuration for production (stdout)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}

AUTH_USER_MODEL = 'authorization.User'

# authentication redirects (namespaced URLs)
LOGIN_URL = 'authorization:login'
LOGIN_REDIRECT_URL = 'authorization:profile'
LOGOUT_REDIRECT_URL = 'authorization:login'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Mercado Pago configuration (public key used in frontend, access token used server-side)
# these should be provided via environment variables for security
MERCADO_PAGO_PUBLIC_KEY = os.environ.get('MERCADO_PAGO_PUBLIC_KEY', 'APP_USR-d5f8b558-6301-4986-be24-853e2c15f09e')
MERCADO_PAGO_ACCESS_TOKEN = os.environ.get('MERCADO_PAGO_ACCESS_TOKEN', 'APP_USR-5172194930900109-030114-85c2f516ba6236eca794c898c5cb547f-2557709656')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

# path where collectstatic will collect files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# whitenoise storage compresses and caches files
# Using the non-strict version to avoid 500 errors if some static files are missing references
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
WHITENOISE_MANIFEST_STRICT = False

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File upload settings
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10 MB
DATA_UPLOAD_MAX_NUMBER_FILES = 1
